# Generated by Django 4.1.5 on 2024-10-08 12:43

import appportfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(blank=True, max_length=30, null=True, verbose_name='Puesto de Trabajo')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nombre_categoria'],
            },
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='titulacion')),
                ('edad', models.IntegerField()),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('nota', models.IntegerField(blank=True, null=True, verbose_name='Nota')),
                ('lugarEstudio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lugar Estudio')),
                ('presencial', models.BooleanField(blank=True, null=True, verbose_name='Presencial')),
                ('observaciones', models.CharField(blank=True, max_length=50, null=True, verbose_name='obsevaciones')),
            ],
            options={
                'verbose_name': 'Estudio',
                'verbose_name_plural': 'Estudios',
                'ordering': ['titulacion'],
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Empresa')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('observaciones', models.CharField(blank=True, max_length=50, null=True, verbose_name='Funciones')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True, verbose_name=appportfolio.models.Categoria)),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
                'ordering': ['empresa'],
            },
        ),
    ]
